package elevate

import (
	"strings"
	"testing"
)

func TestRenderSudoers(t *testing.T) {
	p := mustPolicy(t, `{
	  "rules": [
	    {"allow":"cat","files":["/etc/haproxy/*","/etc/nginx/*"]},
	    {"allow":"sh","verbs":["-c"],"units":["run-*"]},
	    {"allow":"sh","args":["--version"]},
	    {"allow":"apt-get|dnf","args":["-y","*"],"env":["DEBIAN_FRONTEND","LANG"]}
	  ]
	}`)
	out, err := p.RenderSudoers("partout")
	if err != nil {
		t.Fatal(err)
	}
	t.Log(out)

	for _, want := range []string{
		"policy-sha256:",
		"GENERATED by",
		"Cmnd_Alias PARTOUT_CAT =",
		"partout ALL=(root) NOPASSWD:",
		"run-*",
		"--version",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("rendered sudoers missing %q", want)
		}
	}
	// Field feedback F6: wildcards must be UNQUOTED. A quoted "*" in
	// sudoers is a literal asterisk and never matches — every wildcard grant
	// rendered that way was a dead rule (verified empirically on sudo 1.9).
	if strings.Contains(out, `"*"`) {
		t.Errorf("rendered sudoers quotes a wildcard (dead grant): %q", out)
	}
	if strings.Contains(out, `"fail2ban*"`) || strings.Contains(out, `"run-*"`) {
		t.Errorf("rendered sudoers quotes a unit/file glob (dead grant): %q", out)
	}
	if !strings.Contains(out, "/etc/haproxy/*") || !strings.Contains(out, "/etc/nginx/*") {
		t.Error("cat grant missing file globs")
	}
	if strings.Contains(out, "SETENV:") {
		// SETENV lines only expected for the env-bearing rule; make sure the
		// plain cat lines are NOT setenv'd.
		for _, line := range strings.Split(out, "\n") {
			if strings.Contains(line, "PARTOUT_CAT =") || strings.Contains(line, "cat /etc/") {
				if strings.Contains(line, "SETENV:") {
					t.Errorf("cat grant must not be SETENV: %q", line)
				}
			}
		}
	}
	_ = out
}

func TestRenderSudoersDeterministicAndUserScoped(t *testing.T) {
	j := `{"rules":[{"allow":"cat","files":["/x/*"]}]}`
	a := mustPolicy(t, j)
	b := mustPolicy(t, j)
	ra, err := a.RenderSudoers("partout")
	if err != nil {
		t.Fatal(err)
	}
	rb, err := b.RenderSudoers("partout")
	if err != nil {
		t.Fatal(err)
	}
	if ra != rb {
		t.Error("render must be deterministic")
	}
	ru, err := b.RenderSudoers("svcuser")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(ru, "svcuser ALL=(root) NOPASSWD:") {
		t.Error("user not in the grant rule")
	}
	if strings.Contains(ru, "partout ALL=") {
		t.Error("stale user in grant rule")
	}
}

func TestRenderSudoersEmptyPolicy(t *testing.T) {
	var p *Policy
	if _, err := p.RenderSudoers("partout"); err == nil {
		t.Error("nil policy: want error")
	}
	empty := mustPolicy(t, `{"rules":[]}`)
	if _, err := empty.RenderSudoers("partout"); err == nil {
		t.Error("empty policy: want error")
	}
}

// TestRenderSudoersBareCommand (field feedback F11): a rule with no matcher
// grants the zero-argument invocation and must render as `path ""` —
// sudoers' exact "no arguments" specifier. A bare command path alone would
// match ANY arguments (too broad).
func TestRenderSudoersBareCommand(t *testing.T) {
	p := mustPolicy(t, `{"rules":[{"allow":"reboot"}]}`)
	out, err := p.RenderSudoers("partout")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out, `reboot ""`) {
		t.Errorf("bare grant must render as %q, got:\n%s", `reboot ""`, out)
	}
}

// TestBareRuleMatchesZeroArgsOnly (field feedback F11): the agent-side
// matcher for a bare rule: `reboot` matches, `reboot --force` does not.
func TestBareRuleMatchesZeroArgsOnly(t *testing.T) {
	p := mustPolicy(t, `{"rules":[{"allow":"reboot"}]}`)
	if p.Check("reboot", nil) != Elevated {
		t.Error("bare rule must match the zero-arg invocation")
	}
	if p.Check("reboot", []string{"--force"}) == Elevated {
		t.Error("bare rule must NOT match an invocation with arguments")
	}
	if p.Check("shutdown", []string{"-r", "now"}) == Elevated {
		t.Error("bare rule must not match other commands")
	}
}
