// Partout stream protocol (v1).
//
// The AgentStream is a single bidirectional gRPC stream per agent. Events flow
// agent -> server, command/control envelopes flow server -> agent, on one
// authenticated connection (PRD R4, architecture §3).
//
// Envelope framing: each message carries an opaque id, a direction-scoped
// monotonic seq, a correlation id (run_id / request id), an optional TTL, and
// exactly one typed payload (oneof). ACKs reference previously received
// envelopes by id.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/partout/partout.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentStream_Stream_FullMethodName = "/partout.v1.AgentStream/Stream"
)

// AgentStreamClient is the client API for AgentStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentStream is the sole data channel between one agent and the server.
type AgentStreamClient interface {
	// Stream is a bidirectional message stream. The agent initiates the
	// connection, performs the Ed25519 challenge-response handshake (enforced
	// before the first envelope is accepted), then exchanges Envelopes.
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Envelope, Envelope], error)
}

type agentStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentStreamClient(cc grpc.ClientConnInterface) AgentStreamClient {
	return &agentStreamClient{cc}
}

func (c *agentStreamClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Envelope, Envelope], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentStream_ServiceDesc.Streams[0], AgentStream_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Envelope, Envelope]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentStream_StreamClient = grpc.BidiStreamingClient[Envelope, Envelope]

// AgentStreamServer is the server API for AgentStream service.
// All implementations must embed UnimplementedAgentStreamServer
// for forward compatibility.
//
// AgentStream is the sole data channel between one agent and the server.
type AgentStreamServer interface {
	// Stream is a bidirectional message stream. The agent initiates the
	// connection, performs the Ed25519 challenge-response handshake (enforced
	// before the first envelope is accepted), then exchanges Envelopes.
	Stream(grpc.BidiStreamingServer[Envelope, Envelope]) error
	mustEmbedUnimplementedAgentStreamServer()
}

// UnimplementedAgentStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentStreamServer struct{}

func (UnimplementedAgentStreamServer) Stream(grpc.BidiStreamingServer[Envelope, Envelope]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedAgentStreamServer) mustEmbedUnimplementedAgentStreamServer() {}
func (UnimplementedAgentStreamServer) testEmbeddedByValue()                     {}

// UnsafeAgentStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentStreamServer will
// result in compilation errors.
type UnsafeAgentStreamServer interface {
	mustEmbedUnimplementedAgentStreamServer()
}

func RegisterAgentStreamServer(s grpc.ServiceRegistrar, srv AgentStreamServer) {
	// If the following call panics, it indicates UnimplementedAgentStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentStream_ServiceDesc, srv)
}

func _AgentStream_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentStreamServer).Stream(&grpc.GenericServerStream[Envelope, Envelope]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentStream_StreamServer = grpc.BidiStreamingServer[Envelope, Envelope]

// AgentStream_ServiceDesc is the grpc.ServiceDesc for AgentStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "partout.v1.AgentStream",
	HandlerType: (*AgentStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _AgentStream_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/partout/partout.proto",
}
