// Partout stream protocol (v1).
//
// The AgentStream is a single bidirectional gRPC stream per agent. Events flow
// agent -> server, command/control envelopes flow server -> agent, on one
// authenticated connection (PRD R4, architecture §3).
//
// Envelope framing: each message carries an opaque id, a direction-scoped
// monotonic seq, a correlation id (run_id / request id), an optional TTL, and
// exactly one typed payload (oneof). ACKs reference previously received
// envelopes by id.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/partout/partout.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EnvelopeKind tags the oneof payload and its direction.
type EnvelopeKind int32

const (
	EnvelopeKind_ENVELOPE_KIND_UNSPECIFIED EnvelopeKind = 0
	// Up (agent -> server)
	EnvelopeKind_HEARTBEAT      EnvelopeKind = 1
	EnvelopeKind_FACTS_BATCH    EnvelopeKind = 2
	EnvelopeKind_EVENTS_BATCH   EnvelopeKind = 3
	EnvelopeKind_COMMAND_OUTPUT EnvelopeKind = 4
	EnvelopeKind_COMMAND_RESULT EnvelopeKind = 5
	EnvelopeKind_ACK            EnvelopeKind = 6
	// Down (server -> agent)
	EnvelopeKind_COMMAND       EnvelopeKind = 10
	EnvelopeKind_POLICY_BUNDLE EnvelopeKind = 11
	EnvelopeKind_REVOKE        EnvelopeKind = 12
	EnvelopeKind_CANCEL        EnvelopeKind = 13
	// Handshake (per stream)
	EnvelopeKind_CHALLENGE  EnvelopeKind = 40 // down: server issues
	EnvelopeKind_AUTH_PROOF EnvelopeKind = 41 // up: agent replies
)

// Enum value maps for EnvelopeKind.
var (
	EnvelopeKind_name = map[int32]string{
		0:  "ENVELOPE_KIND_UNSPECIFIED",
		1:  "HEARTBEAT",
		2:  "FACTS_BATCH",
		3:  "EVENTS_BATCH",
		4:  "COMMAND_OUTPUT",
		5:  "COMMAND_RESULT",
		6:  "ACK",
		10: "COMMAND",
		11: "POLICY_BUNDLE",
		12: "REVOKE",
		13: "CANCEL",
		40: "CHALLENGE",
		41: "AUTH_PROOF",
	}
	EnvelopeKind_value = map[string]int32{
		"ENVELOPE_KIND_UNSPECIFIED": 0,
		"HEARTBEAT":                 1,
		"FACTS_BATCH":               2,
		"EVENTS_BATCH":              3,
		"COMMAND_OUTPUT":            4,
		"COMMAND_RESULT":            5,
		"ACK":                       6,
		"COMMAND":                   10,
		"POLICY_BUNDLE":             11,
		"REVOKE":                    12,
		"CANCEL":                    13,
		"CHALLENGE":                 40,
		"AUTH_PROOF":                41,
	}
)

func (x EnvelopeKind) Enum() *EnvelopeKind {
	p := new(EnvelopeKind)
	*p = x
	return p
}

func (x EnvelopeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnvelopeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_partout_partout_proto_enumTypes[0].Descriptor()
}

func (EnvelopeKind) Type() protoreflect.EnumType {
	return &file_proto_partout_partout_proto_enumTypes[0]
}

func (x EnvelopeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnvelopeKind.Descriptor instead.
func (EnvelopeKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_partout_partout_proto_rawDescGZIP(), []int{0}
}

type AckStatus int32

const (
	AckStatus_ACK_STATUS_UNSPECIFIED AckStatus = 0
	AckStatus_ACK_OK                 AckStatus = 1
	AckStatus_ACK_DENIED_AGENT       AckStatus = 2 // guardrail re-check failed (down envelope)
)

// Enum value maps for AckStatus.
var (
	AckStatus_name = map[int32]string{
		0: "ACK_STATUS_UNSPECIFIED",
		1: "ACK_OK",
		2: "ACK_DENIED_AGENT",
	}
	AckStatus_value = map[string]int32{
		"ACK_STATUS_UNSPECIFIED": 0,
		"ACK_OK":                 1,
		"ACK_DENIED_AGENT":       2,
	}
)

func (x AckStatus) Enum() *AckStatus {
	p := new(AckStatus)
	*p = x
	return p
}

func (x AckStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AckStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_partout_partout_proto_enumTypes[1].Descriptor()
}

func (AckStatus) Type() protoreflect.EnumType {
	return &file_proto_partout_partout_proto_enumTypes[1]
}

func (x AckStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AckStatus.Descriptor instead.
func (AckStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_partout_partout_proto_rawDescGZIP(), []int{1}
}

type OutputStream int32

const (
	OutputStream_OUTPUT_STREAM_UNSPECIFIED OutputStream = 0
	OutputStream_OUTPUT_STDOUT             OutputStream = 1
	OutputStream_OUTPUT_STDERR             OutputStream = 2
)

// Enum value maps for OutputStream.
var (
	OutputStream_name = map[int32]string{
		0: "OUTPUT_STREAM_UNSPECIFIED",
		1: "OUTPUT_STDOUT",
		2: "OUTPUT_STDERR",
	}
	OutputStream_value = map[string]int32{
		"OUTPUT_STREAM_UNSPECIFIED": 0,
		"OUTPUT_STDOUT":             1,
		"OUTPUT_STDERR":             2,
	}
)

func (x OutputStream) Enum() *OutputStream {
	p := new(OutputStream)
	*p = x
	return p
}

func (x OutputStream) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OutputStream) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_partout_partout_proto_enumTypes[2].Descriptor()
}

func (OutputStream) Type() protoreflect.EnumType {
	return &file_proto_partout_partout_proto_enumTypes[2]
}

func (x OutputStream) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OutputStream.Descriptor instead.
func (OutputStream) EnumDescriptor() ([]byte, []int) {
	return file_proto_partout_partout_proto_rawDescGZIP(), []int{2}
}

// Envelope is the single message type on the stream.
type Envelope struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Id      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // unique per envelope
	Kind    EnvelopeKind           `protobuf:"varint,2,opt,name=kind,proto3,enum=partout.v1.EnvelopeKind" json:"kind,omitempty"`
	Seq     uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`                        // per-direction monotonic (ordering / loss)
	CorrId  string                 `protobuf:"bytes,4,opt,name=corr_id,json=corrId,proto3" json:"corr_id,omitempty"`     // run_id / request correlation
	TtlUnix int64                  `protobuf:"varint,5,opt,name=ttl_unix,json=ttlUnix,proto3" json:"ttl_unix,omitempty"` // expiry for queued down envelopes
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_Heartbeat
	//	*Envelope_Facts
	//	*Envelope_Events
	//	*Envelope_Output
	//	*Envelope_Result
	//	*Envelope_Ack
	//	*Envelope_Command
	//	*Envelope_PolicyBundle
	//	*Envelope_Revoke
	//	*Envelope_Cancel
	//	*Envelope_Challenge
	//	*Envelope_AuthProof
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_proto_partout_partout_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_partout_partout_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_proto_partout_partout_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Envelope) GetKind() EnvelopeKind {
	if x != nil {
		return x.Kind
	}
	return EnvelopeKind_ENVELOPE_KIND_UNSPECIFIED
}

func (x *Envelope) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Envelope) GetCorrId() string {
	if x != nil {
		return x.CorrId
	}
	return ""
}

func (x *Envelope) GetTtlUnix() int64 {
	if x != nil {
		return x.TtlUnix
	}
	return 0
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *Envelope) GetFacts() *FactsBatch {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Facts); ok {
			return x.Facts
		}
	}
	return nil
}

func (x *Envelope) GetEvents() *EventsBatch {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Events); ok {
			return x.Events
		}
	}
	return nil
}

func (x *Envelope) GetOutput() *CommandOutput {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Output); ok {
			return x.Output
		}
	}
	return nil
}

func (x *Envelope) GetResult() *CommandResult {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *Envelope) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *Envelope) GetCommand() *Command {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *Envelope) GetPolicyBundle() *PolicyBundle {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_PolicyBundle); ok {
			return x.PolicyBundle
		}
	}
	return nil
}

func (x *Envelope) GetRevoke() *Revoke {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Revoke); ok {
			return x.Revoke
		}
	}
	return nil
}

func (x *Envelope) GetCancel() *Cancel {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

func (x *Envelope) GetChallenge() *Challenge {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Challenge); ok {
			return x.Challenge
		}
	}
	return nil
}

func (x *Envelope) GetAuthProof() *AuthProof {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_AuthProof); ok {
			return x.AuthProof
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_Heartbeat struct {
	// Up
	Heartbeat *Heartbeat `protobuf:"bytes,20,opt,name=heartbeat,proto3,oneof"`
}

type Envelope_Facts struct {
	Facts *FactsBatch `protobuf:"bytes,21,opt,name=facts,proto3,oneof"`
}

type Envelope_Events struct {
	Events *EventsBatch `protobuf:"bytes,22,opt,name=events,proto3,oneof"`
}

type Envelope_Output struct {
	Output *CommandOutput `protobuf:"bytes,23,opt,name=output,proto3,oneof"`
}

type Envelope_Result struct {
	Result *CommandResult `protobuf:"bytes,24,opt,name=result,proto3,oneof"`
}

type Envelope_Ack struct {
	Ack *Ack `protobuf:"bytes,25,opt,name=ack,proto3,oneof"`
}

type Envelope_Command struct {
	// Down
	Command *Command `protobuf:"bytes,30,opt,name=command,proto3,oneof"`
}

type Envelope_PolicyBundle struct {
	PolicyBundle *PolicyBundle `protobuf:"bytes,31,opt,name=policy_bundle,json=policyBundle,proto3,oneof"`
}

type Envelope_Revoke struct {
	Revoke *Revoke `protobuf:"bytes,32,opt,name=revoke,proto3,oneof"`
}

type Envelope_Cancel struct {
	Cancel *Cancel `protobuf:"bytes,33,opt,name=cancel,proto3,oneof"`
}

type Envelope_Challenge struct {
	// Handshake
	Challenge *Challenge `protobuf:"bytes,50,opt,name=challenge,proto3,oneof"`
}

type Envelope_AuthProof struct {
	AuthProof *AuthProof `protobuf:"bytes,51,opt,name=auth_proof,json=authProof,proto3,oneof"`
}

func (*Envelope_Heartbeat) isEnvelope_Payload() {}

func (*Envelope_Facts) isEnvelope_Payload() {}

func (*Envelope_Events) isEnvelope_Payload() {}

func (*Envelope_Output) isEnvelope_Payload() {}

func (*Envelope_Result) isEnvelope_Payload() {}

func (*Envelope_Ack) isEnvelope_Payload() {}

func (*Envelope_Command) isEnvelope_Payload() {}

func (*Envelope_PolicyBundle) isEnvelope_Payload() {}

func (*Envelope_Revoke) isEnvelope_Payload() {}

func (*Envelope_Cancel) isEnvelope_Payload() {}

func (*Envelope_Challenge) isEnvelope_Payload() {}

func (*Envelope_AuthProof) isEnvelope_Payload() {}

// Ack is sent by the receiver of an envelope to confirm delivery (and, for
// down envelopes, the guardrail re-check outcome).
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvelopeId    string                 `protobuf:"bytes,1,opt,name=envelope_id,json=envelopeId,proto3" json:"envelope_id,omitempty"` // id of the envelope being acknowledged
	Status        AckStatus              `protobuf:"varint,2,opt,name=status,proto3,enum=partout.v1.AckStatus" json:"status,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_partout_partout_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_partout_partout_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_partout_partout_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetEnvelopeId() string {
	if x != nil {
		return x.EnvelopeId
	}
	return ""
}

func (x *Ack) GetStatus() AckStatus {
	if x != nil {
		return x.Status
	}
	return AckStatus_ACK_STATUS_UNSPECIFIED
}

func (x *Ack) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type Heartbeat struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentVersion   string                 `protobuf:"bytes,1,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	UptimeS        int64                  `protobuf:"varint,2,opt,name=uptime_s,json=uptimeS,proto3" json:"uptime_s,omitempty"`
	SpoolMemBytes  int64                  `protobuf:"varint,3,opt,name=spool_mem_bytes,json=spoolMemBytes,proto3" json:"spool_mem_bytes,omitempty"`
	SpoolDiskBytes int64                  `protobuf:"varint,4,opt,name=spool_disk_bytes,json=spoolDiskBytes,proto3" json:"spool_disk_bytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_partout_partout_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_partout_partout_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_partout_partout_proto_rawDescGZIP(), []int{2}
}

func (x *Heartbeat) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Heartbeat) GetUptimeS() int64 {
	if x != nil {
		return x.UptimeS
	}
	return 0
}

func (x *Heartbeat) GetSpoolMemBytes() int64 {
	if x != nil {
		return x.SpoolMemBytes
	}
	return 0
}

func (x *Heartbeat) GetSpoolDiskBytes() int64 {
	if x != nil {
		return x.SpoolDiskBytes
	}
	return 0
}

type FactsBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Full          bool                   `protobuf:"varint,2,opt,name=full,proto3" json:"full,omitempty"` // full snapshot vs. delta
	Facts         map[string]string      `protobuf:"bytes,3,rep,name=facts,proto3" json:"facts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FactsBatch) Reset() {
	*x = FactsBatch{}
	mi := &file_proto_partout_partout_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactsBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactsBatch) ProtoMessage() {}

func (x *FactsBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_partout_partout_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactsBatch.ProtoReflect.Descriptor instead.
func (*FactsBatch) Descriptor() ([]byte, []int) {
	return file_proto_partout_partout_proto_rawDescGZIP(), []int{3}
}

func (x *FactsBatch) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *FactsBatch) GetFull() bool {
	if x != nil {
		return x.Full
	}
	return false
}

func (x *FactsBatch) GetFacts() map[string]string {
	if x != nil {
		return x.Facts
	}
	return nil
}

type EventsBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventsBatch) Reset() {
	*x = EventsBatch{}
	mi := &file_proto_partout_partout_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsBatch) ProtoMessage() {}

func (x *EventsBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_partout_partout_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsBatch.ProtoReflect.Descriptor instead.
func (*EventsBatch) Descriptor() ([]byte, []int) {
	return file_proto_partout_partout_proto_rawDescGZIP(), []int{4}
}

func (x *EventsBatch) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"` // e.g. "container.state", "endpoint.down"
	Ts            int64                  `protobuf:"varint,2,opt,name=ts,proto3" json:"ts,omitempty"`    // epoch seconds
	Attrs         map[string]string      `protobuf:"bytes,3,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_partout_partout_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_partout_partout_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_partout_partout_proto_rawDescGZIP(), []int{5}
}

func (x *Event) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Event) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *Event) GetAttrs() map[string]string {
	if x != nil {
		return x.Attrs
	}
	return nil
}

type CommandOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	ChunkSeq      uint64                 `protobuf:"varint,2,opt,name=chunk_seq,json=chunkSeq,proto3" json:"chunk_seq,omitempty"`
	Stream        OutputStream           `protobuf:"varint,3,opt,name=stream,proto3,enum=partout.v1.OutputStream" json:"stream,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandOutput) Reset() {
	*x = CommandOutput{}
	mi := &file_proto_partout_partout_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandOutput) ProtoMessage() {}

func (x *CommandOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_partout_partout_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandOutput.ProtoReflect.Descriptor instead.
func (*CommandOutput) Descriptor() ([]byte, []int) {
	return file_proto_partout_partout_proto_rawDescGZIP(), []int{6}
}

func (x *CommandOutput) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *CommandOutput) GetChunkSeq() uint64 {
	if x != nil {
		return x.ChunkSeq
	}
	return 0
}

func (x *CommandOutput) GetStream() OutputStream {
	if x != nil {
		return x.Stream
	}
	return OutputStream_OUTPUT_STREAM_UNSPECIFIED
}

func (x *CommandOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"` // succeeded|failed|timed_out|cancelled|interrupted
	DurationMs    int64                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_proto_partout_partout_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_partout_partout_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_proto_partout_partout_proto_rawDescGZIP(), []int{7}
}

func (x *CommandResult) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *CommandResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CommandResult) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CommandResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type Decision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	BundleVersion uint64                 `protobuf:"varint,2,opt,name=bundle_version,json=bundleVersion,proto3" json:"bundle_version,omitempty"`
	Effect        string                 `protobuf:"bytes,3,opt,name=effect,proto3" json:"effect,omitempty"` // "allow" | "deny" | "require_approval"
	MatchedRules  []string               `protobuf:"bytes,4,rep,name=matched_rules,json=matchedRules,proto3" json:"matched_rules,omitempty"`
	Sig           []byte                 `protobuf:"bytes,5,opt,name=sig,proto3" json:"sig,omitempty"`                              // server Ed25519 signature (agent verifies)
	ActorRole     string                 `protobuf:"bytes,6,opt,name=actor_role,json=actorRole,proto3" json:"actor_role,omitempty"` // requester RBAC role (for agent re-eval)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Decision) Reset() {
	*x = Decision{}
	mi := &file_proto_partout_partout_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decision) ProtoMessage() {}

func (x *Decision) ProtoReflect() protoreflect.Message {
	mi := &file_proto_partout_partout_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decision.ProtoReflect.Descriptor instead.
func (*Decision) Descriptor() ([]byte, []int) {
	return file_proto_partout_partout_proto_rawDescGZIP(), []int{8}
}

func (x *Decision) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Decision) GetBundleVersion() uint64 {
	if x != nil {
		return x.BundleVersion
	}
	return 0
}

func (x *Decision) GetEffect() string {
	if x != nil {
		return x.Effect
	}
	return ""
}

func (x *Decision) GetMatchedRules() []string {
	if x != nil {
		return x.MatchedRules
	}
	return nil
}

func (x *Decision) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *Decision) GetActorRole() string {
	if x != nil {
		return x.ActorRole
	}
	return ""
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	ExecutionId   string                 `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Cmd           string                 `protobuf:"bytes,3,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Args          []string               `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	Cwd           string                 `protobuf:"bytes,5,opt,name=cwd,proto3" json:"cwd,omitempty"`
	User          string                 `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	TimeoutS      int32                  `protobuf:"varint,7,opt,name=timeout_s,json=timeoutS,proto3" json:"timeout_s,omitempty"`
	Env           map[string]string      `protobuf:"bytes,8,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Retryable     bool                   `protobuf:"varint,9,opt,name=retryable,proto3" json:"retryable,omitempty"`
	Decision      *Decision              `protobuf:"bytes,10,opt,name=decision,proto3" json:"decision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_proto_partout_partout_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_proto_partout_partout_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_proto_partout_partout_proto_rawDescGZIP(), []int{9}
}

func (x *Command) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Command) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *Command) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *Command) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Command) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *Command) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Command) GetTimeoutS() int32 {
	if x != nil {
		return x.TimeoutS
	}
	return 0
}

func (x *Command) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *Command) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *Command) GetDecision() *Decision {
	if x != nil {
		return x.Decision
	}
	return nil
}

type PolicyBundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	ContentHash   string                 `protobuf:"bytes,2,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	RulesJson     string                 `protobuf:"bytes,3,opt,name=rules_json,json=rulesJson,proto3" json:"rules_json,omitempty"`                                                                        // rules only, never secrets
	ServerPubkey  []byte                 `protobuf:"bytes,4,opt,name=server_pubkey,json=serverPubkey,proto3" json:"server_pubkey,omitempty"`                                                               // server Ed25519 public key (b64) — signs Decisions
	HostTags      map[string]string      `protobuf:"bytes,5,rep,name=host_tags,json=hostTags,proto3" json:"host_tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // this agent's tags (for local re-eval)
	HostRoles     []string               `protobuf:"bytes,6,rep,name=host_roles,json=hostRoles,proto3" json:"host_roles,omitempty"`                                                                        // this agent's roles (for local re-eval)
	AgentId       string                 `protobuf:"bytes,7,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                                                                              // server-assigned agent ID (for host:<id> predicates)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyBundle) Reset() {
	*x = PolicyBundle{}
	mi := &file_proto_partout_partout_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyBundle) ProtoMessage() {}

func (x *PolicyBundle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_partout_partout_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyBundle.ProtoReflect.Descriptor instead.
func (*PolicyBundle) Descriptor() ([]byte, []int) {
	return file_proto_partout_partout_proto_rawDescGZIP(), []int{10}
}

func (x *PolicyBundle) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PolicyBundle) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *PolicyBundle) GetRulesJson() string {
	if x != nil {
		return x.RulesJson
	}
	return ""
}

func (x *PolicyBundle) GetServerPubkey() []byte {
	if x != nil {
		return x.ServerPubkey
	}
	return nil
}

func (x *PolicyBundle) GetHostTags() map[string]string {
	if x != nil {
		return x.HostTags
	}
	return nil
}

func (x *PolicyBundle) GetHostRoles() []string {
	if x != nil {
		return x.HostRoles
	}
	return nil
}

func (x *PolicyBundle) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type Revoke struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Revoke) Reset() {
	*x = Revoke{}
	mi := &file_proto_partout_partout_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Revoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Revoke) ProtoMessage() {}

func (x *Revoke) ProtoReflect() protoreflect.Message {
	mi := &file_proto_partout_partout_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Revoke.ProtoReflect.Descriptor instead.
func (*Revoke) Descriptor() ([]byte, []int) {
	return file_proto_partout_partout_proto_rawDescGZIP(), []int{11}
}

func (x *Revoke) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Cancel asks the agent to stop an in-flight run (kills the process and
// reports state=cancelled).
type Cancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cancel) Reset() {
	*x = Cancel{}
	mi := &file_proto_partout_partout_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cancel) ProtoMessage() {}

func (x *Cancel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_partout_partout_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cancel.ProtoReflect.Descriptor instead.
func (*Cancel) Descriptor() ([]byte, []int) {
	return file_proto_partout_partout_proto_rawDescGZIP(), []int{12}
}

func (x *Cancel) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

// Challenge is issued by the server at stream open (architecture §3.1).
type Challenge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         []byte                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`                        // 32 random bytes
	ServerTs      int64                  `protobuf:"varint,2,opt,name=server_ts,json=serverTs,proto3" json:"server_ts,omitempty"` // server epoch seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Challenge) Reset() {
	*x = Challenge{}
	mi := &file_proto_partout_partout_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Challenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Challenge) ProtoMessage() {}

func (x *Challenge) ProtoReflect() protoreflect.Message {
	mi := &file_proto_partout_partout_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Challenge.ProtoReflect.Descriptor instead.
func (*Challenge) Descriptor() ([]byte, []int) {
	return file_proto_partout_partout_proto_rawDescGZIP(), []int{13}
}

func (x *Challenge) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *Challenge) GetServerTs() int64 {
	if x != nil {
		return x.ServerTs
	}
	return 0
}

// AuthProof is the agent's reply. sig = ed25519_sign(nonce || uuid || ts_be64).
type AuthProof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentUuid     string                 `protobuf:"bytes,1,opt,name=agent_uuid,json=agentUuid,proto3" json:"agent_uuid,omitempty"`
	Ts            int64                  `protobuf:"varint,2,opt,name=ts,proto3" json:"ts,omitempty"` // agent epoch seconds (skew check ±300s)
	Sig           []byte                 `protobuf:"bytes,3,opt,name=sig,proto3" json:"sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthProof) Reset() {
	*x = AuthProof{}
	mi := &file_proto_partout_partout_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthProof) ProtoMessage() {}

func (x *AuthProof) ProtoReflect() protoreflect.Message {
	mi := &file_proto_partout_partout_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthProof.ProtoReflect.Descriptor instead.
func (*AuthProof) Descriptor() ([]byte, []int) {
	return file_proto_partout_partout_proto_rawDescGZIP(), []int{14}
}

func (x *AuthProof) GetAgentUuid() string {
	if x != nil {
		return x.AgentUuid
	}
	return ""
}

func (x *AuthProof) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *AuthProof) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

var File_proto_partout_partout_proto protoreflect.FileDescriptor

const file_proto_partout_partout_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/partout/partout.proto\x12\n" +
	"partout.v1\"\xff\x05\n" +
	"\bEnvelope\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x18.partout.v1.EnvelopeKindR\x04kind\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\x12\x17\n" +
	"\acorr_id\x18\x04 \x01(\tR\x06corrId\x12\x19\n" +
	"\bttl_unix\x18\x05 \x01(\x03R\attlUnix\x125\n" +
	"\theartbeat\x18\x14 \x01(\v2\x15.partout.v1.HeartbeatH\x00R\theartbeat\x12.\n" +
	"\x05facts\x18\x15 \x01(\v2\x16.partout.v1.FactsBatchH\x00R\x05facts\x121\n" +
	"\x06events\x18\x16 \x01(\v2\x17.partout.v1.EventsBatchH\x00R\x06events\x123\n" +
	"\x06output\x18\x17 \x01(\v2\x19.partout.v1.CommandOutputH\x00R\x06output\x123\n" +
	"\x06result\x18\x18 \x01(\v2\x19.partout.v1.CommandResultH\x00R\x06result\x12#\n" +
	"\x03ack\x18\x19 \x01(\v2\x0f.partout.v1.AckH\x00R\x03ack\x12/\n" +
	"\acommand\x18\x1e \x01(\v2\x13.partout.v1.CommandH\x00R\acommand\x12?\n" +
	"\rpolicy_bundle\x18\x1f \x01(\v2\x18.partout.v1.PolicyBundleH\x00R\fpolicyBundle\x12,\n" +
	"\x06revoke\x18  \x01(\v2\x12.partout.v1.RevokeH\x00R\x06revoke\x12,\n" +
	"\x06cancel\x18! \x01(\v2\x12.partout.v1.CancelH\x00R\x06cancel\x125\n" +
	"\tchallenge\x182 \x01(\v2\x15.partout.v1.ChallengeH\x00R\tchallenge\x126\n" +
	"\n" +
	"auth_proof\x183 \x01(\v2\x15.partout.v1.AuthProofH\x00R\tauthProofB\t\n" +
	"\apayload\"m\n" +
	"\x03Ack\x12\x1f\n" +
	"\venvelope_id\x18\x01 \x01(\tR\n" +
	"envelopeId\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.partout.v1.AckStatusR\x06status\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\"\x9d\x01\n" +
	"\tHeartbeat\x12#\n" +
	"\ragent_version\x18\x01 \x01(\tR\fagentVersion\x12\x19\n" +
	"\buptime_s\x18\x02 \x01(\x03R\auptimeS\x12&\n" +
	"\x0fspool_mem_bytes\x18\x03 \x01(\x03R\rspoolMemBytes\x12(\n" +
	"\x10spool_disk_bytes\x18\x04 \x01(\x03R\x0espoolDiskBytes\"\xac\x01\n" +
	"\n" +
	"FactsBatch\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x12\n" +
	"\x04full\x18\x02 \x01(\bR\x04full\x127\n" +
	"\x05facts\x18\x03 \x03(\v2!.partout.v1.FactsBatch.FactsEntryR\x05facts\x1a8\n" +
	"\n" +
	"FactsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"8\n" +
	"\vEventsBatch\x12)\n" +
	"\x06events\x18\x01 \x03(\v2\x11.partout.v1.EventR\x06events\"\x99\x01\n" +
	"\x05Event\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x0e\n" +
	"\x02ts\x18\x02 \x01(\x03R\x02ts\x122\n" +
	"\x05attrs\x18\x03 \x03(\v2\x1c.partout.v1.Event.AttrsEntryR\x05attrs\x1a8\n" +
	"\n" +
	"AttrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x89\x01\n" +
	"\rCommandOutput\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1b\n" +
	"\tchunk_seq\x18\x02 \x01(\x04R\bchunkSeq\x120\n" +
	"\x06stream\x18\x03 \x01(\x0e2\x18.partout.v1.OutputStreamR\x06stream\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"z\n" +
	"\rCommandResult\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\"\xb6\x01\n" +
	"\bDecision\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12%\n" +
	"\x0ebundle_version\x18\x02 \x01(\x04R\rbundleVersion\x12\x16\n" +
	"\x06effect\x18\x03 \x01(\tR\x06effect\x12#\n" +
	"\rmatched_rules\x18\x04 \x03(\tR\fmatchedRules\x12\x10\n" +
	"\x03sig\x18\x05 \x01(\fR\x03sig\x12\x1d\n" +
	"\n" +
	"actor_role\x18\x06 \x01(\tR\tactorRole\"\xe4\x02\n" +
	"\aCommand\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12!\n" +
	"\fexecution_id\x18\x02 \x01(\tR\vexecutionId\x12\x10\n" +
	"\x03cmd\x18\x03 \x01(\tR\x03cmd\x12\x12\n" +
	"\x04args\x18\x04 \x03(\tR\x04args\x12\x10\n" +
	"\x03cwd\x18\x05 \x01(\tR\x03cwd\x12\x12\n" +
	"\x04user\x18\x06 \x01(\tR\x04user\x12\x1b\n" +
	"\ttimeout_s\x18\a \x01(\x05R\btimeoutS\x12.\n" +
	"\x03env\x18\b \x03(\v2\x1c.partout.v1.Command.EnvEntryR\x03env\x12\x1c\n" +
	"\tretryable\x18\t \x01(\bR\tretryable\x120\n" +
	"\bdecision\x18\n" +
	" \x01(\v2\x14.partout.v1.DecisionR\bdecision\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcb\x02\n" +
	"\fPolicyBundle\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12!\n" +
	"\fcontent_hash\x18\x02 \x01(\tR\vcontentHash\x12\x1d\n" +
	"\n" +
	"rules_json\x18\x03 \x01(\tR\trulesJson\x12#\n" +
	"\rserver_pubkey\x18\x04 \x01(\fR\fserverPubkey\x12C\n" +
	"\thost_tags\x18\x05 \x03(\v2&.partout.v1.PolicyBundle.HostTagsEntryR\bhostTags\x12\x1d\n" +
	"\n" +
	"host_roles\x18\x06 \x03(\tR\thostRoles\x12\x19\n" +
	"\bagent_id\x18\a \x01(\tR\aagentId\x1a;\n" +
	"\rHostTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\" \n" +
	"\x06Revoke\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\x1f\n" +
	"\x06Cancel\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\">\n" +
	"\tChallenge\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\x12\x1b\n" +
	"\tserver_ts\x18\x02 \x01(\x03R\bserverTs\"L\n" +
	"\tAuthProof\x12\x1d\n" +
	"\n" +
	"agent_uuid\x18\x01 \x01(\tR\tagentUuid\x12\x0e\n" +
	"\x02ts\x18\x02 \x01(\x03R\x02ts\x12\x10\n" +
	"\x03sig\x18\x03 \x01(\fR\x03sig*\xe7\x01\n" +
	"\fEnvelopeKind\x12\x1d\n" +
	"\x19ENVELOPE_KIND_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tHEARTBEAT\x10\x01\x12\x0f\n" +
	"\vFACTS_BATCH\x10\x02\x12\x10\n" +
	"\fEVENTS_BATCH\x10\x03\x12\x12\n" +
	"\x0eCOMMAND_OUTPUT\x10\x04\x12\x12\n" +
	"\x0eCOMMAND_RESULT\x10\x05\x12\a\n" +
	"\x03ACK\x10\x06\x12\v\n" +
	"\aCOMMAND\x10\n" +
	"\x12\x11\n" +
	"\rPOLICY_BUNDLE\x10\v\x12\n" +
	"\n" +
	"\x06REVOKE\x10\f\x12\n" +
	"\n" +
	"\x06CANCEL\x10\r\x12\r\n" +
	"\tCHALLENGE\x10(\x12\x0e\n" +
	"\n" +
	"AUTH_PROOF\x10)*I\n" +
	"\tAckStatus\x12\x1a\n" +
	"\x16ACK_STATUS_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06ACK_OK\x10\x01\x12\x14\n" +
	"\x10ACK_DENIED_AGENT\x10\x02*S\n" +
	"\fOutputStream\x12\x1d\n" +
	"\x19OUTPUT_STREAM_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rOUTPUT_STDOUT\x10\x01\x12\x11\n" +
	"\rOUTPUT_STDERR\x10\x022G\n" +
	"\vAgentStream\x128\n" +
	"\x06Stream\x12\x14.partout.v1.Envelope\x1a\x14.partout.v1.Envelope(\x010\x01B,Z*github.com/blawesom/partout/internal/protob\x06proto3"

var (
	file_proto_partout_partout_proto_rawDescOnce sync.Once
	file_proto_partout_partout_proto_rawDescData []byte
)

func file_proto_partout_partout_proto_rawDescGZIP() []byte {
	file_proto_partout_partout_proto_rawDescOnce.Do(func() {
		file_proto_partout_partout_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_partout_partout_proto_rawDesc), len(file_proto_partout_partout_proto_rawDesc)))
	})
	return file_proto_partout_partout_proto_rawDescData
}

var file_proto_partout_partout_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_partout_partout_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_partout_partout_proto_goTypes = []any{
	(EnvelopeKind)(0),     // 0: partout.v1.EnvelopeKind
	(AckStatus)(0),        // 1: partout.v1.AckStatus
	(OutputStream)(0),     // 2: partout.v1.OutputStream
	(*Envelope)(nil),      // 3: partout.v1.Envelope
	(*Ack)(nil),           // 4: partout.v1.Ack
	(*Heartbeat)(nil),     // 5: partout.v1.Heartbeat
	(*FactsBatch)(nil),    // 6: partout.v1.FactsBatch
	(*EventsBatch)(nil),   // 7: partout.v1.EventsBatch
	(*Event)(nil),         // 8: partout.v1.Event
	(*CommandOutput)(nil), // 9: partout.v1.CommandOutput
	(*CommandResult)(nil), // 10: partout.v1.CommandResult
	(*Decision)(nil),      // 11: partout.v1.Decision
	(*Command)(nil),       // 12: partout.v1.Command
	(*PolicyBundle)(nil),  // 13: partout.v1.PolicyBundle
	(*Revoke)(nil),        // 14: partout.v1.Revoke
	(*Cancel)(nil),        // 15: partout.v1.Cancel
	(*Challenge)(nil),     // 16: partout.v1.Challenge
	(*AuthProof)(nil),     // 17: partout.v1.AuthProof
	nil,                   // 18: partout.v1.FactsBatch.FactsEntry
	nil,                   // 19: partout.v1.Event.AttrsEntry
	nil,                   // 20: partout.v1.Command.EnvEntry
	nil,                   // 21: partout.v1.PolicyBundle.HostTagsEntry
}
var file_proto_partout_partout_proto_depIdxs = []int32{
	0,  // 0: partout.v1.Envelope.kind:type_name -> partout.v1.EnvelopeKind
	5,  // 1: partout.v1.Envelope.heartbeat:type_name -> partout.v1.Heartbeat
	6,  // 2: partout.v1.Envelope.facts:type_name -> partout.v1.FactsBatch
	7,  // 3: partout.v1.Envelope.events:type_name -> partout.v1.EventsBatch
	9,  // 4: partout.v1.Envelope.output:type_name -> partout.v1.CommandOutput
	10, // 5: partout.v1.Envelope.result:type_name -> partout.v1.CommandResult
	4,  // 6: partout.v1.Envelope.ack:type_name -> partout.v1.Ack
	12, // 7: partout.v1.Envelope.command:type_name -> partout.v1.Command
	13, // 8: partout.v1.Envelope.policy_bundle:type_name -> partout.v1.PolicyBundle
	14, // 9: partout.v1.Envelope.revoke:type_name -> partout.v1.Revoke
	15, // 10: partout.v1.Envelope.cancel:type_name -> partout.v1.Cancel
	16, // 11: partout.v1.Envelope.challenge:type_name -> partout.v1.Challenge
	17, // 12: partout.v1.Envelope.auth_proof:type_name -> partout.v1.AuthProof
	1,  // 13: partout.v1.Ack.status:type_name -> partout.v1.AckStatus
	18, // 14: partout.v1.FactsBatch.facts:type_name -> partout.v1.FactsBatch.FactsEntry
	8,  // 15: partout.v1.EventsBatch.events:type_name -> partout.v1.Event
	19, // 16: partout.v1.Event.attrs:type_name -> partout.v1.Event.AttrsEntry
	2,  // 17: partout.v1.CommandOutput.stream:type_name -> partout.v1.OutputStream
	20, // 18: partout.v1.Command.env:type_name -> partout.v1.Command.EnvEntry
	11, // 19: partout.v1.Command.decision:type_name -> partout.v1.Decision
	21, // 20: partout.v1.PolicyBundle.host_tags:type_name -> partout.v1.PolicyBundle.HostTagsEntry
	3,  // 21: partout.v1.AgentStream.Stream:input_type -> partout.v1.Envelope
	3,  // 22: partout.v1.AgentStream.Stream:output_type -> partout.v1.Envelope
	22, // [22:23] is the sub-list for method output_type
	21, // [21:22] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_proto_partout_partout_proto_init() }
func file_proto_partout_partout_proto_init() {
	if File_proto_partout_partout_proto != nil {
		return
	}
	file_proto_partout_partout_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_Heartbeat)(nil),
		(*Envelope_Facts)(nil),
		(*Envelope_Events)(nil),
		(*Envelope_Output)(nil),
		(*Envelope_Result)(nil),
		(*Envelope_Ack)(nil),
		(*Envelope_Command)(nil),
		(*Envelope_PolicyBundle)(nil),
		(*Envelope_Revoke)(nil),
		(*Envelope_Cancel)(nil),
		(*Envelope_Challenge)(nil),
		(*Envelope_AuthProof)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_partout_partout_proto_rawDesc), len(file_proto_partout_partout_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_partout_partout_proto_goTypes,
		DependencyIndexes: file_proto_partout_partout_proto_depIdxs,
		EnumInfos:         file_proto_partout_partout_proto_enumTypes,
		MessageInfos:      file_proto_partout_partout_proto_msgTypes,
	}.Build()
	File_proto_partout_partout_proto = out.File
	file_proto_partout_partout_proto_goTypes = nil
	file_proto_partout_partout_proto_depIdxs = nil
}
